ShahbazWebsite_MVCPlatform/Controllers/BookingsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ShahbazWebsite_MVCPlatform.Models;

namespace ShahbazWebsite_MVCPlatform.Controllers
{
    public class BookingsController : Controller
    {
        private readonly comp313MVCDatabaseContext _context;

        public BookingsController(comp313MVCDatabaseContext context)
        {
            _context = context;
        }

        // GET: Bookings - Show All
        public async Task<IActionResult> Index()
        {
            if (TempData.ContainsKey(key: "EmployeeLogin"))
            {

            var comp313MVCDatabaseContext = _context.Booking.Include(b => b.User);
            return View(await comp313MVCDatabaseContext.ToListAsync());

            }
            else
            {
               
                return RedirectToAction("Login", "Login");
            }

        }

        // GET: Bookings/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var booking = await _context.Booking
                .Include(b => b.User)
                .SingleOrDefaultAsync(m => m.BookingId == id);
            if (booking == null)
            {
                return NotFound();
            }

            return View(booking);
        }

        // GET: Bookings/Create
        public IActionResult Create()
        {
            ViewData["UserId"] = new SelectList(_context.User, "UserId", "UserId");
            return View();
        }

        // POST: Bookings/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("BookingId,UserId,Category,StartDate,EndDate,TimeFrom,TimeTo,BookingDetail,Status")] Booking booking)
        {
            if (ModelState.IsValid)
            {
                _context.Add(booking);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["UserId"] = new SelectList(_context.User, "UserId", "UserId", booking.UserId);
            return View(booking);
        }

        // GET: Bookings/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var booking = await _context.Booking.SingleOrDefaultAsync(m => m.BookingId == id);
            if (booking == null)
            {
                return NotFound();
            }
            ViewData["UserId"] = new SelectList(_context.User, "UserId", "UserId", booking.UserId);
            return View(booking);
        }

         // ** FIXED 
        [HttpPost]
        public IActionResult EditFixed(Booking model)
            {

                    _context.Update(model);
                    _context.SaveChanges();

            return View("Edit", model);
            }


        // POST: Bookings/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("BookingId,UserId,Category,StartDate,EndDate,TimeFrom,TimeTo,BookingDetail,Status")] Booking booking)
        {
            if (id != booking.BookingId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(booking);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!BookingExists(booking.BookingId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["UserId"] = new SelectList(_context.User, "UserId", "UserId", booking.UserId);
            return View(booking);
        }

        // GET: Bookings/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var booking = await _context.Booking
                .Include(b => b.User)
                .SingleOrDefaultAsync(m => m.BookingId == id);
            if (booking == null)
            {
                return NotFound();
            }

            return View(booking);
        }

        // ** FIXED 
        [HttpPost]
        public IActionResult DeleteConfirmedFixed (Booking model)
            {

                _context.Remove(model);
                _context.SaveChanges();

            return RedirectToAction(nameof(Index));

            }

        // POST: Bookings/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var booking = await _context.Booking.SingleOrDefaultAsync(m => m.BookingId == id);
            _context.Booking.Remove(booking);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool BookingExists(int id)
        {
            return _context.Booking.Any(e => e.BookingId == id);
        }
    }
}

ShahbazWebsite_MVCPlatform/Controllers/TenantController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace ShahbazWebsite_MVCPlatform.Controllers
{
    public class TenantController : Controller
    {
        public IActionResult Index()
        {
            // Login check
            // If logged in, continue
            if (TempData.ContainsKey(key: "TenantLogin"))
            {

                return View();
            }
            else
            {
                // Take to Login page
                // Login action, in Login controller
                return RedirectToAction("Login", "Login");
            }
        }

        public IActionResult RequestsAndBookings()
        {
            if (TempData.ContainsKey(key: "TenantLogin"))
            {

                return View();
            }
            else
            {

                return RedirectToAction("Login", "Login");
            }
        }

        public IActionResult MaintenanceRequests()
        {
            if (TempData.ContainsKey(key: "TenantLogin"))
            {

                return View();
            }
            else
            {

                return RedirectToAction("Login", "Login");
            }
        }

        public IActionResult WebPayment()
        {
            if (TempData.ContainsKey(key: "TenantLogin"))
            {

                return View();
            }
            else
            {

                return RedirectToAction("Login", "Login");
            }
        }

        public IActionResult PasswordReset()
        {
            if (TempData.ContainsKey(key: "TenantLogin"))
            {

                return View();
            }
            else
            {

                return RedirectToAction("Login", "Login");
            }
        }



    }
}

ShahbazWebsite_MVCPlatform/Controllers/UsersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ShahbazWebsite_MVCPlatform.Models;

namespace ShahbazWebsite_MVCPlatform.Controllers
{
    public class UsersController : Controller
    {
        private readonly comp313MVCDatabaseContext _context;

        public UsersController(comp313MVCDatabaseContext context)
        {
            _context = context;
        }

        // GET: Users
        public async Task<IActionResult> Index()
        {
             if (TempData.ContainsKey(key: "EmployeeLogin"))
            {

            return View(await _context.User.ToListAsync());

              }
             
            else
            {
               
                return RedirectToAction("Login", "Login");
            }

        }

        // GET: Users/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var user = await _context.User
                .SingleOrDefaultAsync(m => m.UserId == id);
            if (user == null)
            {
                return NotFound();
            }

            return View(user);
        }

        // GET: Users/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Users/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("UserId,FirstName,LastName,Email,PhoneNumber,ApartmentNumber,UserType,Password")] User user)
        {
            if (ModelState.IsValid)
            {
                _context.Add(user);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(user);
        }

        // GET: Users/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var user = await _context.User.SingleOrDefaultAsync(m => m.UserId == id);
            if (user == null)
            {
                return NotFound();
            }
            return View(user);
        }


        // ** FIXED 
        [HttpPost]
        public IActionResult EditFixed(User model)
            {

                    _context.Update(model);
                    _context.SaveChanges();

            return View("Edit", model);
            }


        // POST: Users/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("UserId,FirstName,LastName,Email,PhoneNumber,ApartmentNumber,UserType,Password")] User user)
        {
            if (id != user.UserId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(user);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!UserExists(user.UserId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(user);
        }

        // GET: Users/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var user = await _context.User
                .SingleOrDefaultAsync(m => m.UserId == id);
            if (user == null)
            {
                return NotFound();
            }

            return View(user);
        }

        // ** FIXED 
        [HttpPost]
        public IActionResult DeleteConfirmedFixed (User model)
            {

                _context.Remove(model);
                _context.SaveChanges();

            return RedirectToAction(nameof(Index));

            }


        // POST: Users/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var user = await _context.User.SingleOrDefaultAsync(m => m.UserId == id);
            _context.User.Remove(user);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool UserExists(int id)
        {
            return _context.User.Any(e => e.UserId == id);
        }
    }
}

ShahbazWebsite_MVCPlatform/Views/Shared/_Layout.cshtml


@*This layout is used by Views in Employee and Reporting folders

    BOOTSTRAP - Multiple navbars:
    https://stackoverflow.com/questions/21616381/multiple-fixed-top-navbar-headers-in-twitter-bootstrap-3*@

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title>@ViewData["Title"] - Employee</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>

    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container-fluid">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#employeeNav">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" asp-controller="Employee" asp-action="Index">Employee Management</a>
            </div>
            <div class"collapse navbar-collapse" id="employeeNav">
                <ul class="nav navbar-nav">
                    <li class="dropdown">
                        <a class="dropdown-toggle" data-toggle="dropdown" href="#">Employee Actions<span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li><a asp-area="" asp-controller="Users" asp-action="Index">User Management</a></li>
                            <li><a asp-area="" asp-controller="Bookings" asp-action="Index">Bookings And Requests</a></li>
                            <li><a asp-area="" asp-controller="Maintenances" asp-action="Index">Maintenance Requests</a></li>
                        </ul>
                    </li>
                    <li class="dropdown">
                        <a class="dropdown-toggle" data-toggle="dropdown" href="#">Reporting<span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li><a asp-area="" asp-controller="Reporting" asp-action="Reports_DailyRequestsAndBookings">Daily Requests & Bookings</a></li>
                            <li><a asp-area="" asp-controller="Reporting" asp-action="Reports_Maintenance">Maintenance</a></li>
                            <li><a asp-area="" asp-controller="Reporting" asp-action="Reports_TenantSearch">Tenant Search And Details</a></li>
                            <li><a asp-area="" asp-controller="Reporting" asp-action="Reports_WebPayments">Web Payments</a></li>
                            <li><a asp-area="" asp-controller="Reporting" asp-action="Reports_AggregateData">Aggregate data</a></li>
                        </ul>
                    </li>
                    <li class="dropdown">
                        <a class="dropdown-toggle" data-toggle="dropdown" href="#">Timelines and Workflow<span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li><a asp-area="" asp-controller="Timelines" asp-action="TimelinesBookings_Months">Bookings (monthly)</a></li>
                            <li><a asp-area="" asp-controller="Timelines" asp-action="TimelinesMaintenances_Months">Maintenances (monthly)</a></li>
                            <li><a asp-area="" asp-controller="Timelines" asp-action="TimelinesBookings_Weeks">Bookings (weekly)</a></li>
                            <li><a asp-area="" asp-controller="Timelines" asp-action="TimelinesMaintenances_Weeks">Maintenances (weekly)</a></li>
                        </ul>
                    </li>
                    <li><a asp-area="" asp-controller="Login" asp-action="LogoutPerformed">Logout</a></li>
                </ul>
            </div>
        </div>
    </nav>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <br />
        <br />
        <br />
        <footer>
            <p>&copy; 2018 - CondoManagementMVCcoreApplication</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>

ShahbazWebsite_MVCPlatform/Views/Shared/_Layout_TimelinesBookings_Months.cshtml
    <!DOCTYPE html>
    <html>
    <head>

        <meta charset='utf-8' />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />

        <title>@ViewData["Title"]</title>

        <environment include="Development">
            <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
            <link rel="stylesheet" href="~/css/site.css" />
        </environment>
        <environment exclude="Development">
            <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
                  asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
                  asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
            <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
        </environment>

        @*FullCalendar.io css and scripts loaded:*@
        <link href='~/css/fullcalendar.css' rel='stylesheet' />
        <link href='~/css/fullcalendar.print.css' rel='stylesheet' media='print' />
        <script src='~/lib/moment.min.js'></script>
        <script src='~/lib/jquery.min.js'></script>
        <script src='~/js/fullcalendar.js'></script>



        @*FullCalendar.io JQuery script running to fill div with id = "calendar" in body: *@
        <script>

            $(document).ready(function () {

                $('#calendar').fullCalendar({
                    header: {
                        left: 'prev,next today',
                        center: 'title',
                        right: 'month'
                    },
                    defaultDate: '2018-04-01',
                    firstDay: '01', // 01 = Monday
                    defaultView: 'month',
                    navLinks: true, // can click day/week/month names to navigate views
                    editable: false,
                    eventLimit: false, // allow "more" link when too many events
                    contentHeight: 700,

                    eventRender: function (event, element, view) {

                        if (event.type == "Parking" || event.type == "parking"
                                                    || event.type == "Guest Parking"
                                                    || event.type == "guest parking") {

                            $(element).find('.fc-content').prepend("&nbsp;")
                                .prepend('<img src="/images/parking.png" width="22" height="22" />')
                                .prepend("&nbsp; &nbsp;");
                        }

                        if (event.type == "Party Hall" || event.type == "party hall") {
                                                                                        

                            $(element).find('.fc-content').prepend("&nbsp;")
                                .prepend('<img src="/images/music.png" width="20" height="20" />')
                                .prepend('<img src="/images/partyhall.png" width="20" height="20" />')
                                .prepend("&nbsp; &nbsp;");
                        }

                        if (event.status == "Approved" || event.status == "approved" ) {

                            $(element).find('.fc-content').prepend("&nbsp; &nbsp;");

                            $(element).find('.fc-content').append("&nbsp; &nbsp;")
                                .append('<img src="/images/check.png" width="12" height="12" />');

                        }



                    },

                    eventSources: [

                        {

                            // JSON data feed link
                            url: '/Timelines/TimelinesBookings_JSON'
                            
                            // Note: no "~" in url, we are in JQuery world
                        }

                    ]

                });

            });

        </script>



        <style>


            body {
                /*margin: 40px 10px;*/
                /*padding: 0;*/
                font-family: "Lucida Grande",Helvetica,Arial,Verdana,sans-serif;
                /*font-size: 17px;*/
            }

            #calendar {
                /*max-width: 900px;*/
                margin: 0 auto;
            }
        </style>
    </head>
    <body>

       
        <nav class="navbar navbar-inverse navbar-fixed-top">
            <div class="container-fluid">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bookNav">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" asp-controller="Employee" asp-action="Index">Employee Management</a>
                </div>
                <div class"collapse navbar-collapse" id="bookNav">
                    <ul class="nav navbar-nav">
                        <li class="dropdown">
                            <a class="dropdown-toggle" data-toggle="dropdown" href="#">Employee Actions<span class="caret"></span></a>
                            <ul class="dropdown-menu">
                                <li><a asp-area="" asp-controller="Users" asp-action="Index">User Management</a></li>
                                <li><a asp-area="" asp-controller="Bookings" asp-action="Index">Bookings And Requests</a></li>
                                <li><a asp-area="" asp-controller="Maintenances" asp-action="Index">Maintenance Requests</a></li>
                            </ul>
                        </li>
                        <li class="dropdown">
                            <a class="dropdown-toggle" data-toggle="dropdown" href="#">Reporting<span class="caret"></span></a>
                            <ul class="dropdown-menu">
                                <li><a asp-area="" asp-controller="Reporting" asp-action="Reports_DailyRequestsAndBookings">Daily Requests & Bookings</a></li>
                                <li><a asp-area="" asp-controller="Reporting" asp-action="Reports_Maintenance">Maintenance</a></li>
                                <li><a asp-area="" asp-controller="Reporting" asp-action="Reports_TenantSearch">Tenant Search And Details</a></li>
                                <li><a asp-area="" asp-controller="Reporting" asp-action="Reports_WebPayments">Web Payments</a></li>
                                <li><a asp-area="" asp-controller="Reporting" asp-action="Reports_AggregateData">Aggregate data</a></li>
                            </ul>
                        </li>
                        <li class="dropdown">
                            <a class="dropdown-toggle" data-toggle="dropdown" href="#">Timelines and Workflow<span class="caret"></span></a>
                            <ul class="dropdown-menu">
                                <li><a asp-area="" asp-controller="Timelines" asp-action="TimelinesBookings_Months">Bookings (monthly)</a></li>
                                <li><a asp-area="" asp-controller="Timelines" asp-action="TimelinesMaintenances_Months">Maintenances (monthly)</a></li>
                                <li><a asp-area="" asp-controller="Timelines" asp-action="TimelinesBookings_Weeks">Bookings (weekly)</a></li>
                                <li><a asp-area="" asp-controller="Timelines" asp-action="TimelinesMaintenances_Weeks">Maintenances (weekly)</a></li>

                            </ul>
                        </li>
                        <li><a asp-area="" asp-controller="Login" asp-action="LogoutPerformed">Logout</a></li>
                    </ul>
                </div>
            </div>
        </nav>

        <div class="container body-content">
            @RenderBody()
            <hr />
            <br />
            <br />
            <br />
            <footer>
                <p>&copy; 2018 - CondoManagementMVCcoreApplication</p>
            </footer>
        </div>

        <environment include="Development">
            <script src="~/lib/jquery/dist/jquery.js"></script>
            <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
            <script src="~/js/site.js" asp-append-version="true"></script>
            <script src='~/lib/moment.min.js'></script>
            <script src='~/lib/jquery.min.js'></script>
            <script src='~/js/fullcalendar.js'></script>
        </environment>

    </body>
</html>

ShahbazWebsite_MVCPlatform/Views/Shared/_TenantLayout.cshtml
@*This layout is used by Views in Employee and Reporting folders*@

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title>@ViewData["Title"] - Tenant</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>

    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container-fluid">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#tenantNav">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" asp-controller="Tenant" asp-action="Index">Tenant Management</a>
            </div>
            <div class"collapse navbar-collapse" id="tenantNav">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="TenantBookings" asp-action="Index">Requests & Bookings</a></li>
                    <li><a asp-area="" asp-controller="TenantMaintenances" asp-action="Index">Maintenance Requests </a></li>
                    <li><a asp-area="" asp-controller="TenantPayments" asp-action="Index">Payments</a></li>
                    <li><a asp-area="" asp-controller="Login" asp-action="LogoutPerformed">Logout</a></li>
                </ul>
            </div>
        </div>
    </nav>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <br />
        <br />
        <br />
        <footer>
            <p>&copy; 2018 - CondoManagementMVCcoreApplication</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>