ShahbazWebsite_MVCPlatform/Controllers/ReportingController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ShahbazWebsite_MVCPlatform.Models;

namespace ShahbazWebsite_MVCPlatform.Controllers


{
    public class ReportingController : Controller
    {


        private readonly comp313MVCDatabaseContext _context;

        public ReportingController(comp313MVCDatabaseContext context)
        {
            _context = context;
        }

        // Default index - Nothing yet
        public IActionResult Reporting()
        {
            return View();
        }

          // GET: Bookings and Requests report - Show all data
        public async Task<IActionResult> Reports_DailyRequestsAndBookings()
        {

            if (TempData.ContainsKey(key: "EmployeeLogin"))
            {

            var comp313MVCDatabaseContext = _context.Booking.Include(b => b.User);
            return View(await comp313MVCDatabaseContext.ToListAsync());

            }
            else
            {
               
                return RedirectToAction("Login", "Login");
            }


        }

           // GET: Maintenances report - Show all data
        public async Task<IActionResult> Reports_Maintenance()
        {

             if (TempData.ContainsKey(key: "EmployeeLogin"))
            {

            var comp313MVCDatabaseContext = _context.Maintenance.Include(m => m.User);
            return View(await comp313MVCDatabaseContext.ToListAsync());
             
            }
             
            else
            {
               
                return RedirectToAction("Login", "Login");
            }
        }


         // POST
        public IActionResult Reports_TenantSearchDetails(string TenantSearch)
        {

             if (TempData.ContainsKey(key: "EmployeeLogin"))
            {

                // For the view
                ViewData["TenantSearchRequested"] = TenantSearch;

                // Returning this model 
                var reportModel = new Reporting_UserDetails();


                //1. If only numbers, then let's do User.Id lookup
                //   NEXT: null checking in TenantSearch

                    if (System.Text.RegularExpressions.Regex.IsMatch(TenantSearch, "^[0-9]*$"))
                        {

                                // User.Id lookup in DB
                                var user =  _context.User.SingleOrDefault(m => m.UserId == Convert.ToInt32(TenantSearch));

                                        if (user == null)
                                        {
                                            ViewData["Message"] = "Not found in DB";
                                             reportModel = null;
                                        }else
                                                {
                                                //ViewData["UserFound"] = user.UserId;
                                                
                                               
                                                reportModel.User = user;
                                                
                                                var bookingList = _context.Booking
                                                                            .ToList()
                                                                            .Where(b => b.UserId == user.UserId);
                                                                            
                                                reportModel.Booking = bookingList;


                                                var maintenanceList = _context.Maintenance.ToList().Where(m => m.UserId == user.UserId); 
                                                reportModel.Maintenance = maintenanceList;


                                                var paymentList =_context.Payment.ToList().Where(p => p.UserId == user.UserId);
                                                reportModel.Payment = paymentList;
                                                
                                                }

                                

                        }

                    //1. If only letters and contains a space, then let's do user.FirstName and user.LastName lookup
                    //   NEXT: null checking in TenantSearch

                    if (System.Text.RegularExpressions.Regex.IsMatch(TenantSearch, "^[A-Za-z ]+$") && TenantSearch.Contains(" "))
                        {

                                // Split full name entered in search into 2
                                string[] names = TenantSearch.Split(" ");
                                string firstname = names[0];
                                string lastname = names[1];
                                
                                // user.FirstName and user.LastName lookup in DB
                                var user =  _context.User.SingleOrDefault(u => u.FirstName == firstname &&
                                                                               u.LastName == lastname);

                                        if (user == null)
                                        {
                                            ViewData["Message"] = "Not found in DB";
                                            reportModel = null;
                                        }else
                                                {
                                                //ViewData["UserFound"] = user.FirstName + " " + user.LastName;

                                                reportModel.User = user;
                                                
                                                var bookingList = _context.Booking
                                                                            .ToList()
                                                                            .Where(b => b.UserId == user.UserId);
                                                                            
                                                reportModel.Booking = bookingList;


                                                var maintenanceList = _context.Maintenance.ToList().Where(m => m.UserId == user.UserId); 
                                                reportModel.Maintenance = maintenanceList;


                                                var paymentList =_context.Payment.ToList().Where(p => p.UserId == user.UserId);
                                                reportModel.Payment = paymentList;
                                                }

                                

                        }


           
                    // If text entered in search is null

                    if (TenantSearch == null)
                    {
                    ViewData["Message"] = "Text entered is null";
                    reportModel = null;
                    }

                    // If only single word
                    if (System.Text.RegularExpressions.Regex.IsMatch(TenantSearch, "^[A-Za-z ]+$") && !TenantSearch.Contains(" "))
                    {
                    ViewData["Message"] = "Try entering first and last name both, or ID.  For example, John Smith or 128";

                    reportModel = null;
                    }

                     // If both number+text has been entered, e.g. (abc123)
                    if (System.Text.RegularExpressions.Regex.IsMatch(TenantSearch, "^([0-9]+[a-zA-Z]+|[a-zA-Z]+[0-9]+)[0-9a-zA-Z]*$") 
                                                                        && !TenantSearch.Contains(" "))
                    {
                    ViewData["Message"] = "Try entering text only with first and last name both. Or just enter ID.  For example, John Smith or 128";

                    reportModel = null;
                    }


                    
                   

                return View(reportModel);

                 }
             
            else
            {
               
                return RedirectToAction("Login", "Login");
            }

            
        }

        public IActionResult Reports_TenantSearch()
        {
            if (TempData.ContainsKey(key: "EmployeeLogin"))
            {

                return View();

                }
             
            else
            {
               
                return RedirectToAction("Login", "Login");
            }


            
        }


        // Web Paments report - Show all data
        public async Task<IActionResult> Reports_WebPayments()
        {

         if (TempData.ContainsKey(key: "EmployeeLogin"))
            {

            var comp313MVCDatabaseContext = _context.Payment.Include(p => p.User);

            // Return entire list of payments
            return View(await comp313MVCDatabaseContext.ToListAsync());


          }
             
            else
            {
               
                return RedirectToAction("Login", "Login");
            }

        }


        public IActionResult Reports_AggregateData()
        {
                
             if (TempData.ContainsKey(key: "EmployeeLogin"))
            {

                // Returning this model 
                var reportmodel = new Reporting_Aggregates();

                reportmodel.User_TotalEmployees =  _context.User.Count(u => u.UserType == "Employee" ||  u.UserType == "employee");
                reportmodel.User_TotalTenants =  _context.User.Count(u => u.UserType == "Tenant" ||  u.UserType == "tenant");

                reportmodel.Booking_TotalParking =  _context.Booking.Count(b => b.Category == "Parking" ||  b.Category == "parking");
                reportmodel.Booking_TotalGuestParking =  _context.Booking.Count(b => b.Category == "Guest Parking" ||  b.Category == "guest parking"

ShahbazWebsite_MVCPlatform/Views/Reporting/Reports_AggregateData.cshtml
@model ShahbazWebsite_MVCPlatform.Models.Reporting_Aggregates

@{
    ViewData["Title"] = "Reports - AggregateData";
}


<br />

<div style="color:rgb(0, 102, 102)"><strong>AGGREGATE DATA:</strong></div>

<!--Line, yellow colored-->
<div style="width: 300px; height: 5px; border-bottom: 4px solid rgb(255, 233, 26); position: absolute"></div>

<br />

<table style="width: 50%; border-width: 2px">
    <tr>
        <td style="background-color:rgb(0, 102, 102); color:white">Users - Employees </td>
        <td style="background-color: rgb(229,234,238);text-align:center">@Html.DisplayFor(model => model.User_TotalEmployees)</td>
    </tr>
    <tr>
        <td style="background-color:rgb(0, 102, 102); color:white">Users - Tenants </td>
        <td style="background-color: rgb(229,234,238);text-align:center">@Html.DisplayFor(model => model.User_TotalTenants)</td>
    </tr>
</table>

<br />

<table style="width: 60%; border-width: 2px">
    <tr>
        <td style="background-color:rgb(0, 102, 102); color:white">Bookings/Requests - Parking </td>
        <td style="background-color: rgb(229,234,238);text-align:center">@Html.DisplayFor(model => model.Booking_TotalParking)</td>
    </tr>
    <tr>
        <td style="background-color:rgb(0, 102, 102); color:white">Bookings/Requests - Guest Parking </td>
        <td style="background-color: rgb(229,234,238);text-align:center">@Html.DisplayFor(model => model.Booking_TotalGuestParking)</td>
    </tr>
    <tr>
        <td style="background-color:rgb(0, 102, 102); color:white">Bookings/Requests - Party Hall</td>
        <td style="background-color: rgb(229,234,238);text-align:center">@Html.DisplayFor(model => model.Booking_TotalPartyHall)</td>
    </tr>
</table>



<br />

<table style="width: 80%; border-width: 2px">
    <tr>
        <td style="background-color:rgb(0, 102, 102); color:white">Maintenance - Repair </td>
        <td style="background-color: rgb(229,234,238);text-align:center">@Html.DisplayFor(model => model.Maintenance_TotalRepair)</td>
    </tr>
    <tr>
        <td style="background-color:rgb(0, 102, 102); color:white">Maintenance - Emergency </td>
        <td style="background-color: rgb(229,234,238);text-align:center">@Html.DisplayFor(model => model.Maintenance_TotalEmergency)</td>
    </tr>
    <tr>
        <td style="background-color:rgb(0, 102, 102); color:white">Maintenance - Electrical </td>
        <td style="background-color: rgb(229,234,238);text-align:center">@Html.DisplayFor(model => model.Maintenance_TotalElectrical)</td>
    </tr>
    <tr>
        <td style="background-color:rgb(0, 102, 102); color:white">Maintenance - Plumbing </td>
        <td style="background-color: rgb(229,234,238);text-align:center">@Html.DisplayFor(model => model.Maintenance_TotalPlumbing)</td>
    </tr>
    <tr>
        <td style="background-color:rgb(0, 102, 102); color:white">Maintenance - HVAC (Heating, Venting, Air Conditioning) </td>
        <td style="background-color: rgb(229,234,238);text-align:center">@Html.DisplayFor(model => model.Maintenance_TotalHVAC)</td>
    </tr>
    <tr>
        <td style="background-color:rgb(0, 102, 102); color:white">Maintenance - Cleaning </td>
        <td style="background-color: rgb(229,234,238);text-align:center">@Html.DisplayFor(model => model.Maintenance_TotalCleaning)</td>
    </tr>
    <tr>
        <td style="background-color:rgb(0, 102, 102); color:white">Maintenance - Amount Paid by Condominium (total) </td>
        <td style="background-color: rgb(229,234,238);text-align:center">$ @Html.DisplayFor(model => model.Maintenance_TotalDollarAmount)</td>
    </tr>
</table>


<br />

<table style="width: 60%; border-width: 2px">
    <tr>
        <td style="background-color:rgb(0, 102, 102); color:white">Payments - Paying users </td>
        <td style="background-color: rgb(229,234,238);text-align:center">@Html.DisplayFor(model => model.Payment_TotalUsers)</td>
    </tr>
    <tr>
        <td style="background-color:rgb(0, 102, 102); color:white">Payments - Total Amount Paid </td>
        <td style="background-color: rgb(229,234,238);text-align:center">
        $ 
        @Html.DisplayFor(model => model.Payment_TotalAmountPaid)
        </td>
    </tr>
    <tr>
        <td style="background-color:rgb(0, 102, 102); color:white">Payments for Rent (By # of Users) </td>
        <td style="background-color: rgb(229,234,238);text-align:center">
        $ 
        @Html.DisplayFor(model => model.Payment_TotalRentPaid)
        ( 
        @Html.DisplayFor(model => model.Payment_TotalUsersRent) 
        )
        </td>
    </tr>
    <tr>
        <td style="background-color:rgb(0, 102, 102); color:white">Payments for - Locker rentals </td>
        <td style="background-color: rgb(229,234,238);text-align:center">$ @Html.DisplayFor(model => model.Payment_TotalLockerRental)</td>
    </tr>
    <tr>
        <td style="background-color:rgb(0, 102, 102); color:white">Payments for - Premium cleaning </td>
        <td style="background-color: rgb(229,234,238);text-align:center">$ @Html.DisplayFor(model => model.Payment_TotalPremiumCleaning)</td>
    </tr>

</table>

ShahbazWebsite_MVCPlatform/Views/Reporting/Reports_DailyRequestsAndBookings.cshtml
@model IEnumerable<ShahbazWebsite_MVCPlatform.Models.Booking>

    @{
    ViewData["Title"] = "Reports - Daily Requests And Bookings";
    }



    <div style="color:rgb(0, 102, 102)"><strong>DAILY LIST - BOOKINGS & REQUESTS</strong></div>

    <!--Line, yellow colored-->
    <div style="width: 325px; height: 5px; border-bottom: 4px solid rgb(255, 233, 26); position: absolute"></div>


    <br />
    <br />

    <table style="width: 100%; height: 122px; border: 2px solid white">
        <thead>
            <tr style="background-color:rgb(0, 102, 102)">
                <th style="color:white; border: 2px solid white">
                    <strong>@Html.DisplayNameFor(model => model.BookingId)</strong>
                </th>
                <th style="color:white; border: 2px solid white">
                    <strong> @Html.DisplayNameFor(model => model.Category)</strong>
                </th>
                <th style="color:white; border: 2px solid white">
                    <strong>@Html.DisplayNameFor(model => model.StartDate)</strong>
                    (for)
                </th>
                <th style="color:white; border: 2px solid white">
                    <strong>@Html.DisplayNameFor(model => model.EndDate)</strong>
                </th>
                <th style="color:white; border: 2px solid white">
                    <strong>@Html.DisplayNameFor(model => model.TimeFrom)</strong>
                </th>
                <th style="color:white; border: 2px solid white">
                    <strong>@Html.DisplayNameFor(model => model.TimeTo)</strong>
                </th>
                <th style="color:white; border: 2px solid white">
                    <strong>@Html.DisplayNameFor(model => model.BookingDetail)</strong>
                </th>
                <th style="color:white; border: 2px solid white">
                    <strong>@Html.DisplayNameFor(model => model.Status)</strong>
                </th>
                <th style="color:white; border: 2px solid white">
                    <strong>@Html.DisplayNameFor(model => model.User.UserId)</strong>
                </th>
                <th style="color:white; border: 2px solid white">
                    <strong>@Html.DisplayNameFor(model => model.User.FirstName)</strong>
                </th>
                <th style="color:white; border: 2px solid white">
                    <strong>@Html.DisplayNameFor(model => model.User.LastName)</strong>
                </th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model) {
            <tr style="background-color: rgb(229,234,238)">
                <td style="border: 2px solid white">
                    @Html.DisplayFor(modelItem => item.BookingId)
                </td>
                <td style="border: 2px solid white">
                    @Html.DisplayFor(modelItem => item.Category)
                </td>
                <td style="border: 2px solid white">
                    @Html.DisplayFor(modelItem => item.StartDate)
                </td>
                <td style="border: 2px solid white">
                    @Html.DisplayFor(modelItem => item.EndDate)
                </td>
                <td style="border: 2px solid white">
                    @Html.DisplayFor(modelItem => item.TimeFrom)
                </td>
                <td style="border: 2px solid white">
                    @Html.DisplayFor(modelItem => item.TimeTo)
                </td>
                <td style="border: 2px solid white">
                    @Html.DisplayFor(modelItem => item.BookingDetail)
                </td>
                <td style="border: 2px solid white">
                    @Html.DisplayFor(modelItem => item.Status)
                </td>
                <td style="border: 2px solid white">
                    @Html.DisplayFor(modelItem => item.User.UserId)
                </td>
                <td style="border: 2px solid white">
                    @Html.DisplayFor(modelItem => item.User.FirstName)
                </td>
                <td style="border: 2px solid white">
                    @Html.DisplayFor(modelItem => item.User.LastName)
                </td>
            </tr>
}
        </tbody>
    </table>

ShahbazWebsite_MVCPlatform/Views/Reporting/Reports_Maintenance.cshtml
@model IEnumerable<ShahbazWebsite_MVCPlatform.Models.Maintenance>

    @{
    ViewData["Title"] = "Reports - Maintenance";

    }

    <div style="color:rgb(0, 102, 102)"><strong>MAINTENANCE - ALL RECORDS (PENDING AND COMPLETED) WITH DOLLAR AMOUNTS</strong></div>

    <!--Line, yellow colored-->
    <div style="width: 825px; height: 5px; border-bottom: 4px solid rgb(255, 233, 26); position: absolute"></div>

    <br />
    <br />


    <table style="width: 100%; height: 122px; border: 2px solid white">
        <thead>
            <tr style="background-color:rgb(0, 102, 102)">
                <th style="color:white; border: 2px solid white">
                    <strong>@Html.DisplayNameFor(model => model.Category)</strong>
                </th>
                <th style="color:white; border: 2px solid white">
                    <strong>@Html.DisplayNameFor(model => model.StartDate)</strong>
                    (created on)
                </th>
                <th style="color:white; border: 2px solid white">
                    <strong>@Html.DisplayNameFor(model => model.EndDate)</strong>
                    (closed on)
                </th>
                <th style="color:white; border: 2px solid white">
                    <strong>@Html.DisplayNameFor(model => model.MaintenanceDetail)</strong>
                </th>
                <th style="color:white; border: 2px solid white">
                    <strong>@Html.DisplayNameFor(model => model.Status)</strong>
                </th>
                <th style="color:white; border: 2px solid white">
                    <strong>@Html.DisplayNameFor(model => model.DollarAmount)</strong>
                </th>
                <th style="color:white; border: 2px solid white">
                    <strong>@Html.DisplayNameFor(model => model.Note)</strong>
                </th>
                <th style="color:white; border: 2px solid white">
                    <strong>@Html.DisplayNameFor(model => model.User.UserId)</strong>
                </th>
                <th style="color:white; border: 2px solid white">
                    <strong>@Html.DisplayNameFor(model => model.User.FirstName)</strong>
                </th>
                <th style="color:white; border: 2px solid white">
                    <strong>@Html.DisplayNameFor(model => model.User.LastName)</strong>
                </th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model) {
            <tr style="background-color: rgb(229,234,238)">
                <td style="border: 2px solid white">
                    @Html.DisplayFor(modelItem => item.Category)
                </td>
                <td style="border: 2px solid white">
                    @Html.DisplayFor(modelItem => item.StartDate)
                </td>
                <td style="border: 2px solid white">
                    @Html.DisplayFor(modelItem => item.EndDate)
                </td>
                <td style="border: 2px solid white">
                    @Html.DisplayFor(modelItem => item.MaintenanceDetail)
                </td>
                <td style="border: 2px solid white">
                    @Html.DisplayFor(modelItem => item.Status)
                </td>
                <td style="border: 2px solid white">
                    @Html.DisplayFor(modelItem => item.DollarAmount)
                </td>
                <td style="border: 2px solid white">
                    @Html.DisplayFor(modelItem => item.Note)
                </td>
                <td style="border: 2px solid white">
                    @Html.DisplayFor(modelItem => item.User.UserId)
                </td>
                <td style="border: 2px solid white">
                    @Html.DisplayFor(modelItem => item.User.FirstName)
                </td>
                <td style="border: 2px solid white">
                    @Html.DisplayFor(modelItem => item.User.LastName)
                </td>
            </tr>
}
        </tbody>
    </table>

ShahbazWebsite_MVCPlatform/Views/Reporting/Reports_TenantSearch.cshtml
@{
    ViewData["Title"] = "Reports - Tenant Search";
}




<br />

<p style="background-color:rgb(0, 102, 102); color:white"><strong>FIND TENANT:</strong>&nbsp;&nbsp;&nbsp;</p>

@*Note: The below method is not passing a model. This is old way of doing MVC.*@

<form asp-action="Reports_TenantSearchDetails" asp-controller="Reporting" method="post">
    <input name="TenantSearch" placeholder="Search full name or ID..." />
    <br />
    <input type="submit" value="Find" />
</form>

ShahbazWebsite_MVCPlatform/Views/Reporting/Reports_TenantSearchDetails.cshtml
@model ShahbazWebsite_MVCPlatform.Models.Reporting_UserDetails

@{
    ViewData["Title"] = "Reports - Tenant Search ";
}


<h2>

    Search entered:

    @ViewData["TenantSearchRequested"]

</h2>

<br />

<h1>

    Result:

    @ViewData["Message"]

</h1>



@if (Model != null)
{

<br />

<div style="color:rgb(0, 102, 102)"><strong>TENANT INFORMATION:</strong></div>

<!--Line, yellow colored-->
<div style="width: 300px; height: 5px; border-bottom: 4px solid rgb(255, 233, 26); position: absolute"></div>

<br />

<table style="width: 80%; height: 122px; border-width: 2px">
    <tbody>
        <tr>
            <td style="background-color:rgb(0, 102, 102); color:white">First Name </td>
            <td style="background-color: rgb(229,234,238)">@Html.DisplayFor(model => model.User.FirstName)</td>
        </tr>
        <tr>
            <td style="background-color:rgb(0, 102, 102); color:white">Last Name </td>
            <td style="background-color: rgb(229,234,238)">@Html.DisplayFor(model => model.User.LastName)</td>

        </tr>
        <tr>
            <td style="background-color:rgb(0, 102, 102); color:white" class="auto-style1">Condo #</td>
            <td style="background-color: rgb(229,234,238)">@Html.DisplayFor(model => model.User.ApartmentNumber)</td>

        </tr>
        <tr>
            <td style="background-color:rgb(0, 102, 102); color:white" class="auto-style1">UserId #</td>
            <td style="background-color: rgb(229,234,238)">@Html.DisplayFor(model => model.User.UserId)</td>

        </tr>
        <tr>
            <td style="background-color:rgb(0, 102, 102); color:white">Phone #</td>
            <td style="background-color: rgb(229,234,238)">@Html.DisplayFor(model => model.User.Password)</td>

        </tr>
        <tr>
            <td style="background-color:rgb(0, 102, 102); color:white">Email</td>
            <td style="background-color: rgb(229,234,238)">@Html.DisplayFor(model => model.User.Email)</td>

        </tr>
    </tbody>
</table>







<br />

<div style="color:rgb(0, 102, 102)"><strong>Recent Bookings and Requests:</strong></div>

<!--Line, yellow colored-->
<div style="width: 300px; height: 5px; border-bottom: 4px solid rgb(255, 233, 26); position: absolute"></div>

<br />



<table style="width: 100%; height: 122px; border: 2px solid white">
    <thead>
        <tr style="background-color:rgb(0, 102, 102)">
            <th style="color:white; border: 2px solid white">
                <strong>Booking ID</strong>
            </th>
            <th style="color:white; border: 2px solid white">
                <strong>Type</strong>
            </th>
            <th style="color:white; border: 2px solid white">
                <strong>BookingDetail</strong>
            </th>
            <th style="color:white; border: 2px solid white">
                <strong>Status</strong>
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.Booking) {
        <tr style="background-color: rgb(229,234,238)">
            <td style="border: 2px solid white">
                @Html.DisplayFor(modelItem => item.BookingId)
            </td>
            <td style="border: 2px solid white">
                @Html.DisplayFor(modelItem => item.Category)
            </td>
            <td style="border: 2px solid white">
                @Html.DisplayFor(modelItem => item.BookingDetail)
            </td>
            <td style="border: 2px solid white">
                @Html.DisplayFor(modelItem => item.Status)
            </td>
        </tr>
    }
    </tbody>
</table>







<br />

<div style="color:rgb(0, 102, 102)"><strong>Recent Maintenance related requests:</strong></div>

<!--Line, yellow colored-->
<div style="width: 300px; height: 5px; border-bottom: 4px solid rgb(255, 233, 26); position: absolute"></div>

<br />



<table style="width: 100%; height: 122px; border: 2px solid white">
    <thead>
        <tr style="background-color:rgb(0, 102, 102)">
            <th style="color:white; border: 2px solid white">
                <strong>Maintenance ID</strong>
            </th>
            <th style="color:white; border: 2px solid white">
                <strong>Type</strong>
            </th>
            <th style="color:white; border: 2px solid white">
                <strong>Status</strong>
            </th>
            <th style="color:white; border: 2px solid white">
                <strong>Note (from staff)</strong>
            </th>
            <th style="color:white; border: 2px solid white">
                <strong>Dollar Amount</strong>
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.Maintenance) {
        <tr style="background-color: rgb(229,234,238)">
            <td style="border: 2px solid white">
                @Html.DisplayFor(modelItem => item.MaintenanceId)
            </td>
            <td style="border: 2px solid white">
                @Html.DisplayFor(modelItem => item.Category)
            </td>
            <td style="border: 2px solid white">
                @Html.DisplayFor(modelItem => item.Status)
            </td>
            <td style="border: 2px solid white">
                @Html.DisplayFor(modelItem => item.Note)
            </td>
            <td style="border: 2px solid white">
                @Html.DisplayFor(modelItem => item.DollarAmount)
            </td>
        </tr>
    }
    </tbody>
</table>





<br />

<div style="color:rgb(0, 102, 102)"><strong>Recent payments:</strong></div>

<!--Line, yellow colored-->
<div style="width: 300px; height: 5px; border-bottom: 4px solid rgb(255, 233, 26); position: absolute"></div>

<br />



<table style="width: 100%; height: 122px; border: 2px solid white">
    <thead>
        <tr style="background-color:rgb(0, 102, 102)">
            <th style="color:white; border: 2px solid white">
                <strong>Payment ID</strong>
            </th>
            <th style="color:white; border: 2px solid white">
                <strong>Type (for)</strong>
            </th>
            <th style="color:white; border: 2px solid white">
                <strong>Amount paid</strong>
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.Payment) {
        <tr style="background-color: rgb(229,234,238)">
            <td style="border: 2px solid white">
                @Html.DisplayFor(modelItem => item.PaymentId)
            </td>
            <td style="border: 2px solid white">
                @Html.DisplayFor(modelItem => item.TypeOfPayment)
            </td>
            <td style="border: 2px solid white">
                @Html.DisplayFor(modelItem => item.AmountPaid)
            </td>
        </tr>
    }
    </tbody>
</table>

}